### ISSUE TITLE
TypeError: pg.connect is not a function

### ISSUE THREAD

**Issue by arvidsnet** [awslabs/aws-lambda-redshift-loader#188]
after update from version 2.6.5 to 2.6.9 (via uploading dist/AWSLambdaRedshiftLoader-2.6.9.zip file) I got the following error:
```
TypeError: pg.connect is not a function
at /var/task/index.js:1196:20
at /var/task/kmsCrypto.js:247:9
at /var/task/node_modules/async/dist/async.js:473:16
at iteratorCallback (/var/task/node_modules/async/dist/async.js:1064:13)
at /var/task/node_modules/async/dist/async.js:969:16
at /var/task/kmsCrypto.js:242:3
at Response.<anonymous> (/var/task/kmsCrypto.js:202:10)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```
tried both Node.js 6.10 and Node.js 8.10.
rolling back to 2.6.5 fixed the issue

**Comment by IanMeyers** [comment]
Looking.

**Comment by IanMeyers** [comment]
The interface of pg has changed in version 7.8.0. I'm building a fix now. Sorry :(

**Comment by IanMeyers** [comment]
I believe this is addressed with 765bb44. Do let me know. Version stays a 2.6.9.

**Comment by arvidsnet** [comment]
yes, it fixed the issue. 
Thank you very much for such quick fix!
